# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersInThisRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.TextField(default='private'),
        ),
        migrations.AddField(
            model_name='usersinthisroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whiteListUsers', to='chat.Room'),
        ),
    ]
