# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20160627_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='label',
            field=models.SlugField(),
        ),
    ]
