# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20160629_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='roomAdmin',
            field=models.TextField(default='steve'),
        ),
    ]
